import type { Metadata } from "next";
import { League_Spartan } from "next/font/google";
import "./globals.css";
import ThemeProvider from "./providers/ThemeProvider";
import { Toaster } from "react-hot-toast";

const leagueSpartan = League_Spartan({
  variable: "--font-league-spartan",
  subsets: ["latin"],
  weight: ["500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${leagueSpartan.variable} antialiased`}>
        <Toaster toastOptions={{ className: "backgroind-red-500" }} />
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
